---
deployment:
  tasks:
    - export REPOPATH=/home/a7890by/repositories/develop/*
    - export SITEPATH=/home/a7890by/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH